# Generated by Django 5.1.7 on 2025-04-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
