# Generated by Django 5.1.7 on 2025-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenges_created',
            field=models.IntegerField(default=0),
        ),
    ]
